### ISSUE TITLE
faceCount and faceHeight options

### ISSUE THREAD

**Issue by mxmzb** [MaKleSoft/wheel-select#1]
I am not sure whether I understand what you mean by "faces". I expected it to be the number of items in the wheel to show, but it seems to be something else, as if I use faceCount="3" the whole wheel disappears instead of showing me one item in the center, one above and one below. Similarly I don't understand what faceHeight parameter does. It seems it actually changes the height, but the number doesn't equal pixels.

**Comment by MaKleSoft** [comment]
Imagine the control like a barrel with the base shape of a polygon. A
'face' corresponds to an edge of the polygon. For example if you choose
faceCount=8 you get a barrel with an octagon for a base shape. Likewise,
'faceHeight' corresponds to the lenth of the polygons edges. The bigger the
face height, the larger the 'barrel'. Does that make any sense to you?

Btw, it's worth pointing out that I haven't touched this repo in quite a
while so it's save to assume it won't work with recent Polymer versions.

**Comment by mxmzb** [comment]
That makes absolutely sense, thank you for the enlightment ;) I don't mind about it not being maintained, also used older (0.5.5) version of polymer so it's fine 👍

**Comment by MaKleSoft** [comment]
Are you using in any live product? I'd love to see it in action somewhere :)

**Comment by mxmzb** [comment]
It's not live yet, but it will be in approximately 2 months I guess, I will let you know when we publish the project (given we don't throw out the script for whatever reasons). :)

**Comment by MaKleSoft** [comment]
Awesome!
